### ISSUE TITLE
Test failing on Url.Parser, Url.Builder - elm 0.18

### ISSUE THREAD

**Issue by pjfitzgibbons** [rtfeldman/elm-spa-example#58]
Hello,
Is the current master branch dependent upon elm .19 ?
I'm receiving this on elm test :
> Executing task: elm test <

I cannot find module 'Url.Parser'.

Module 'Article.Slug' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
Compilation failed while attempting to build /home/fitzpe/programming/elm/elm-spa-example/tests/RoutingTests.elm
The terminal process terminated with exit code: 1

Thoughts anyone?

Thanks,
Peter Fitzgibbons

**Comment by SidneyNemzer** [comment]
Yep, the master branch is on 0.19, it won't compile with 0.18

**Comment by pjfitzgibbons** [comment]
I'm still having trouble with test.  I now installed elm@elm0.19.0 and elm-test@0.19.0-beta4
I'm receiving 

I cannot find module 'Article'.

Module 'RoutingTests' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
Compilation failed while attempting to build /programming/elm/elm-spa-example/tests/RoutingTests.elm

More thoughts?

Thanks for your help!

@SidneyNemzer

**Comment by SidneyNemzer** [comment]
That error message mentions `elm-package.json` which indicates you're still running the 0.18 compiler (0.19 uses `elm.json`).

Check `elm make --version`, it should say something like 0.19

You might also ask on the Elm Slack (http://elmlang.herokuapp.com/), you'll get more people able to help!

**Comment by pjfitzgibbons** [comment]
Progress.  I reinstalled elm@0.19.0-bugfix2 and elm-test@0.19.0-beta4.
Now elm-test compiles/runs, all-fail though, like this :

```
↓ RoutingTests
↓ Route.fromUrl
✗ Parsing hash: ""

    Just Home
    ╷
    │ Expect.equal
    ╵
    Just Root


↓ RoutingTests
↓ Route.fromUrl
✗ Parsing hash: "#login"

    Nothing
    ╷
    │ Expect.equal
    ╵
    Just Login
```
Thoughts?
@SidneyNemzer

**Comment by SidneyNemzer** [comment]
Looks like those are failing tests. I'm not sure if @rtfeldman updated them completely when he rewrote the app a little while ago. For example one of the tests wants `Root` to get parsed but the `Route` module won't return the `Root` route for any URL.
